services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:                # ✅ This line tells Docker to load .env
      - .env
    networks:
      - llm-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge
