services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    buildCommand: ""
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
    buildCommand: ""
    startCommand: "streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0"
